name: Test CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  build:
    name: Terraform Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ secrets.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate